name: deploy to dev

on: 
  push:
    branches:
      - 'main'

jobs:
  deploy:
    uses: kouki-mi/React3dPhotoShelf/.github/workflows/deploy.yml@dev
    secrets:
      IAMROLETOASSUME: ${{ secrets.ROLETOASSUME }}
      DISTRIBUTIONID: ${{ secrets.CLOUDFRONTDISTRIBUTIONID }}
    permissions:
      id-token: write
      contents: read