name: deploy to prod

on: 
  push:
    branches:
      - 'prod'

jobs:
  deploy:
    uses: kouki-mi/React3dPhotoShelf/.github/workflows/deploy.yml@prod
    secrets:
      BRANCH: 'prod'
      IAMROLETOASSUME: ${{ secrets.ROLETOASSUMEPROD }}
      DISTRIBUTIONID: ${{ secrets.CLOUDFRONTDISTRIBUTIONIDPROD }}
    permissions:
        id-token: write
        contents: read